services:
  db:
    container_name: cilist-db
    image: jkpraja/cilist-db:latest
    #build: ./database
    volumes:
      #- ./sosial-media/dump.sql:/etc/mysql/dump.sql
      #- ./database/crud_db.sql:/docker-entrypoint-initdb.d/crud_db.sql
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "docker inspect --format '{{json .State.health.status}}' db | grep 'healthy' || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 10
    #  start_period: 30s
    #command: ["bin/sh", "./entrypoint.sh"]
  frontend:
    container_name: cilist-fe
    image: jkpraja/cilist-fe:latest
    #build: ./frontend
    ports:
      - 80:3000
    #volumes:
    #  - sourcecode:/var/local/apache2/htdocs
    networks:
      - appnet
  backend:
    container_name: cilist-be
    image: jkpraja/cilist-be:latest
    #build: ./backend
    ports:
      - 5000:5000
    #depends_on:
    #  db:
    #    condition: service_completed_successfully
    links:
      - db
    networks:
      - appnet
volumes:
  db-data:
networks:
  appnet: