services:
  db:
    container_name: cilist-db
    image: jkpraja/cilist-db:${GIT_COMMIT_SHORT}
    build: ./database
    volumes:
      #- ./sosial-media/dump.sql:/etc/mysql/dump.sql
      #- ./database/crud_db.sql:/docker-entrypoint-initdb.d/crud_db.sql
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - appnet
    #command: ["bin/sh", "./entrypoint.sh"]
  frontend:
    container_name: cilist-fe
    image: jkpraja/cilist-fe:${GIT_COMMIT_SHORT}
    build: ./frontend
    ports:
      - 80:3000
    #volumes:
    #  - sourcecode:/var/local/apache2/htdocs
    networks:
      - appnet
  backend:
    container_name: cilist-be
    image: jkpraja/cilist-be:${GIT_COMMIT_SHORT}
    build: ./backend
    ports:
      - 5000:5000
    depends_on:
      - db
    links:
      - db
    networks:
      - appnet
volumes:
  db-data:
networks:
  appnet: